name: trade_in_diagnostics_v2
description: Trade-In Diagnostics App
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.0
  vibration: ^2.0.0
  device_info_plus: ^10.1.0
  battery_plus: ^7.0.0
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0
  firebase_crashlytics: ^3.4.9
  connectivity_plus: ^5.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#4F46E5"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
